


<?php

     $con = mysqli_connect('localhost','root','160302');
     $db = mysqli_select_db($con,'montgomery');

     if($con){
      //echo 'Successful to connect to database'.'<br />';
     }
      else{
         echo 'Error to connect to database';
     }

     if($db){
          //echo ' Successful to find montgomery' . '<br />';
     }
      else{
         echo 'Error to find montgomery';
     }

   $choosingValues = $_COOKIE['mycookie'];
   //echo 'Choosing values are '.$choosingValues;
   $chooseValuesAfterSplit = explode(" ",$choosingValues);
   // $chooseValuesAfterSplit is an array, after splitted by space, detais are as follows:
   // [0] = null, [1] = Age, [2] = Language, [3] = Education Qualification, [4] = Business Experience, [5] = Investment Experience,
   // [6] = Net Business and Personal Assets Business, [7] = Business Turnover, [8] = Innovation [9] = State or Territory nomination
   // [10] = return id of Innovation, [11] = sum of scores.
   // var_dump($chooseValuesAfterSplit); decomment this line to check details.

   $firstname = $_POST['firstname'];
   $lastname = $_POST['lastname'];
   $age = $_POST['userage'];
   $telephone = $_POST['usertelephone'];
   $email = $_POST['useremail'];
   $country = $_POST['country'];

   $sql = "INSERT INTO  users (firstname, lastname, age, telephone, email, country, scores)
          VALUES ('$firstname','$lastname','$age','$telephone','$email','$country', '$chooseValuesAfterSplit[11]')";
   if(!mysqli_query($con, $sql))
   {
     echo 'Not Saved, something wrong and redirecting in 8 seconds';
     header("refresh:8; url = page-visa-BM-calculate.html");
   }else {
     echo '<p>Information saved and an Auto-generated Email with your score detail has been sent, redirecting to the main page in 8 seconds</p>';
     header("refresh:8; url = page-visa-BM-calculate.html");
   }

   use PHPMailer\PHPMailer\PHPMailer;
   use PHPMailer\PHPMailer\Exception;

   require 'PHPMailer/src/Exception.php';
   require 'PHPMailer/src/PHPMailer.php';
   require 'PHPMailer/src/SMTP.php';

    $mail = new PHPMailer();
    try {
    //Server settings
    $mail->SMTPDebug = 0;                                 // Enable verbose debug output
    $mail->isSMTP();                                      // Set mailer to use SMTP
    $mail->Host = 'smtp.gmail.com';  // Specify main and backup SMTP servers
    $mail->SMTPAuth = true;                               // Enable SMTP authentication
    $mail->Username = 'adelaideneocs@gmail.com';                 // SMTP username
    $mail->Password = '20160302n**';                           // SMTP password
    $mail->SMTPSecure = 'tls';                            // Enable TLS encryption, `ssl` also accepted
    $mail->Port = 587;                                    // TCP port to connect to
    $mail->setFrom('neoneilcs46@163.com', 'Montgomery');
    $mail->addAddress($email, 'Neo');     // Add a recipient
    $mail->isHTML(true);
    $mail->AddEmbeddedImage('-coresrc/img/header.jpg', 'header.jpg');                               // Set email format to HTML
    $mail->Subject = 'Thanks for consulting Montgomery';
    $mail->Body    = "<h1>Thanks for using self-evaluation of Montgomery</h1>
                      <img alt='Montgomery' style='width: 500px' src=\"cid:header.jpg\" />
                      <p><b>Dear Customer: </b>$firstname $lastname ,</p>
                      <p>This is an Auto-Reply Email generated by officail gmail from Montgomery International Consultants</p>
                      <p>Your immigration score is $chooseValuesAfterSplit[11]</p>
                      <ul>
                       <li>Age: $chooseValuesAfterSplit[1]</li>
                       <li>Language: $chooseValuesAfterSplit[2]</li>
                       <li>Education Qualification: $chooseValuesAfterSplit[3]</li>
                       <li>Business Experience: $chooseValuesAfterSplit[4]</li>
                       <li>Investment Experience: $chooseValuesAfterSplit[5]</li>
                       <li>Net Business and Personal Assets Business: $chooseValuesAfterSplit[6]</li>
                       <li>Business Turnover: $chooseValuesAfterSplit[7]</li>
                       <li>Innovation: $chooseValuesAfterSplit[8]</li>
                       <li>State or Territory nomination: $chooseValuesAfterSplit[9]</li>
                      </ul>
                      <p>Address: xxxxxxxxxxxxxxxx</p>
                      <p>Telephone: xxxxxxxxxxxxxxxx</p>";


    $mail->AltBody = 'This is the body in plain text for non-HTML mail clients';

    $mail->send();
     echo 'Message has been sent';
    } catch (Exception $e) {
     echo 'Message could not be sent.';
     echo 'Mailer Error: ' . $mail->ErrorInfo;
    }

?>
